# coding: utf-8

# flake8: noqa

"""
    Seerr API

    This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

    The version of the OpenAPI document: v3.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0" # x-release-please-version

# Define package exports
__all__ = [
    "AuthApi",
    "BlocklistApi",
    "CollectionApi",
    "IssueApi",
    "MediaApi",
    "MoviesApi",
    "OtherApi",
    "OverrideruleApi",
    "PersonApi",
    "PublicApi",
    "RequestApi",
    "SearchApi",
    "ServiceApi",
    "SettingsApi",
    "TmdbApi",
    "TvApi",
    "UsersApi",
    "WatchlistApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Blocklist",
    "Cast",
    "Certification",
    "CertificationResponse",
    "Collection",
    "Company",
    "CreateAuthJellyfinRequest",
    "CreateAuthLocalRequest",
    "CreateAuthLogout2XXResponse",
    "CreateAuthPlexRequest",
    "CreateAuthResetPasswordByGuidRequest",
    "CreateAuthResetPasswordRequest",
    "CreateIssueCommentRequest",
    "CreateIssueRequest",
    "CreateJellyfinSyncRequest",
    "CreateJobsScheduleRequest",
    "CreateMediaByStatusRequest",
    "CreateRequestRequest",
    "CreateRequestRequestSeasons",
    "CreateUserImportFromJellyfinRequest",
    "CreateUserImportFromPlexRequest",
    "CreateUserRegisterPushSubscriptionRequest",
    "CreateUserRequest",
    "CreateUserSettingsLinkedAccountsJellyfinRequest",
    "CreateUserSettingsPasswordRequest",
    "CreateUserSettingsPermissionsRequest",
    "CreditCast",
    "CreditCrew",
    "Crew",
    "DiscordSettings",
    "DiscordSettingsOptions",
    "DiscoverSlider",
    "Episode",
    "ExternalIds",
    "Genre",
    "GetAbout2XXResponse",
    "GetBlocklist2XXResponse",
    "GetBlocklist2XXResponseResultsInner",
    "GetCache2XXResponse",
    "GetCache2XXResponseApiCachesInner",
    "GetCache2XXResponseApiCachesInnerStats",
    "GetCache2XXResponseDnsCache",
    "GetCache2XXResponseDnsCacheEntriesValue",
    "GetCache2XXResponseDnsCacheEntriesValueAddresses",
    "GetCache2XXResponseDnsCacheStats",
    "GetCache2XXResponseImageCache",
    "GetCache2XXResponseImageCacheTmdb",
    "GetCertificationsMovie500Response",
    "GetDiscoverMovies2XXResponse",
    "GetDiscoverMoviesGenreByGenreId2XXResponse",
    "GetDiscoverMoviesLanguageByLanguage2XXResponse",
    "GetDiscoverMoviesStudioByStudioId2XXResponse",
    "GetDiscoverTv2XXResponse",
    "GetDiscoverTvGenreByGenreId2XXResponse",
    "GetDiscoverTvLanguageByLanguage2XXResponse",
    "GetDiscoverTvNetworkByNetworkId2XXResponse",
    "GetIssue2XXResponse",
    "GetIssueCount2XXResponse",
    "GetJellyfinSync2XXResponse",
    "GetMedia2XXResponse",
    "GetMediaWatchData2XXResponse",
    "GetMediaWatchData2XXResponseData",
    "GetMovieRatings2XXResponse",
    "GetMovieRatingscombined2XXResponse",
    "GetMovieRatingscombined2XXResponseImdb",
    "GetPersonCombinedCredits2XXResponse",
    "GetPlexSync2XXResponse",
    "GetRequestCount2XXResponse",
    "GetSearch2XXResponse",
    "GetSearch2XXResponseResultsInner",
    "GetSearchCompany2XXResponse",
    "GetSearchKeyword2XXResponse",
    "GetServiceRadarrByRadarrId2XXResponse",
    "GetServiceSonarrBySonarrId2XXResponse",
    "GetStatus2XXResponse",
    "GetStatusAppdata2XXResponse",
    "GetTvRatings2XXResponse",
    "GetUser2XXResponse",
    "GetUserPushSubscriptions2XXResponse",
    "GetUserQuota2XXResponse",
    "GetUserQuota2XXResponseMovie",
    "GetUserRequests2XXResponse",
    "GetUserSettingsPassword2XXResponse",
    "GetUserSettingsPermissions2XXResponse",
    "GetUserWatchData2XXResponse",
    "GetUserWatchlist2XXResponse",
    "GetUserWatchlist2XXResponseResultsInner",
    "GotifySettings",
    "GotifySettingsOptions",
    "Issue",
    "IssueComment",
    "JellyfinLibrary",
    "JellyfinSettings",
    "Job",
    "Keyword",
    "ListDiscoverGenresliderMovie2XXResponseInner",
    "ListGenresMovie2XXResponseInner",
    "ListJellyfinUsers2XXResponseInner",
    "ListLanguages2XXResponseInner",
    "ListLogs2XXResponseInner",
    "ListNotificationsPushoverSounds2XXResponseInner",
    "ListPlexUsers2XXResponseInner",
    "ListRegions2XXResponseInner",
    "MainSettings",
    "MediaInfo",
    "MediaRequest",
    "MediaRequestModifiedBy",
    "MetadataSettings",
    "MetadataSettingsSettings",
    "MovieDetails",
    "MovieDetailsCollection",
    "MovieDetailsCredits",
    "MovieDetailsProductionCountriesInner",
    "MovieDetailsReleases",
    "MovieDetailsReleasesResultsInner",
    "MovieDetailsReleasesResultsInnerReleaseDatesInner",
    "MovieResult",
    "Network",
    "NetworkSettings",
    "NetworkSettingsDnsCache",
    "NetworkSettingsProxy",
    "NotificationAgentTypes",
    "NotificationEmailSettings",
    "NotificationEmailSettingsOptions",
    "NtfySettings",
    "NtfySettingsOptions",
    "OverrideRule",
    "PageInfo",
    "PersonDetails",
    "PersonResult",
    "PersonResultKnownForInner",
    "PlexConnection",
    "PlexDevice",
    "PlexLibrary",
    "PlexSettings",
    "ProductionCompany",
    "PublicSettings",
    "PushbulletSettings",
    "PushbulletSettingsOptions",
    "PushoverSettings",
    "PushoverSettingsOptions",
    "PutUserRequest",
    "RadarrSettings",
    "RelatedVideo",
    "Season",
    "ServarrTag",
    "ServiceProfile",
    "SlackSettings",
    "SlackSettingsOptions",
    "SonarrSeries",
    "SonarrSeriesAddOptionsInner",
    "SonarrSeriesImagesInner",
    "SonarrSeriesRatingsInner",
    "SonarrSeriesSeasonsInner",
    "SonarrSettings",
    "SpokenLanguage",
    "TautulliSettings",
    "TelegramSettings",
    "TelegramSettingsOptions",
    "TestMetadatas2XXResponse",
    "TestMetadatasRequest",
    "TestRadarr2XXResponse",
    "TestRadarrRequest",
    "TvDetails",
    "TvDetailsContentRatings",
    "TvDetailsContentRatingsResultsInner",
    "TvDetailsCreatedByInner",
    "TvResult",
    "UpdateDiscoverRequest",
    "UpdateRequestRequest",
    "User",
    "UserSettings",
    "UserSettingsNotifications",
    "WatchProviderDetails",
    "WatchProviderRegion",
    "WatchProvidersInner",
    "Watchlist",
    "WebPushSettings",
    "WebhookSettings",
    "WebhookSettingsOptions",
]

# import apis into sdk package
from seerr.api.auth_api import AuthApi as AuthApi
from seerr.api.blocklist_api import BlocklistApi as BlocklistApi
from seerr.api.collection_api import CollectionApi as CollectionApi
from seerr.api.issue_api import IssueApi as IssueApi
from seerr.api.media_api import MediaApi as MediaApi
from seerr.api.movies_api import MoviesApi as MoviesApi
from seerr.api.other_api import OtherApi as OtherApi
from seerr.api.overriderule_api import OverrideruleApi as OverrideruleApi
from seerr.api.person_api import PersonApi as PersonApi
from seerr.api.public_api import PublicApi as PublicApi
from seerr.api.request_api import RequestApi as RequestApi
from seerr.api.search_api import SearchApi as SearchApi
from seerr.api.service_api import ServiceApi as ServiceApi
from seerr.api.settings_api import SettingsApi as SettingsApi
from seerr.api.tmdb_api import TmdbApi as TmdbApi
from seerr.api.tv_api import TvApi as TvApi
from seerr.api.users_api import UsersApi as UsersApi
from seerr.api.watchlist_api import WatchlistApi as WatchlistApi

# import ApiClient
from seerr.api_response import ApiResponse as ApiResponse
from seerr.api_client import ApiClient as ApiClient
from seerr.configuration import Configuration as Configuration
from seerr.exceptions import OpenApiException as OpenApiException
from seerr.exceptions import ApiTypeError as ApiTypeError
from seerr.exceptions import ApiValueError as ApiValueError
from seerr.exceptions import ApiKeyError as ApiKeyError
from seerr.exceptions import ApiAttributeError as ApiAttributeError
from seerr.exceptions import ApiException as ApiException

# import models into sdk package
from seerr.models.blocklist import Blocklist as Blocklist
from seerr.models.cast import Cast as Cast
from seerr.models.certification import Certification as Certification
from seerr.models.certification_response import CertificationResponse as CertificationResponse
from seerr.models.collection import Collection as Collection
from seerr.models.company import Company as Company
from seerr.models.create_auth_jellyfin_request import CreateAuthJellyfinRequest as CreateAuthJellyfinRequest
from seerr.models.create_auth_local_request import CreateAuthLocalRequest as CreateAuthLocalRequest
from seerr.models.create_auth_logout2_xx_response import CreateAuthLogout2XXResponse as CreateAuthLogout2XXResponse
from seerr.models.create_auth_plex_request import CreateAuthPlexRequest as CreateAuthPlexRequest
from seerr.models.create_auth_reset_password_by_guid_request import CreateAuthResetPasswordByGuidRequest as CreateAuthResetPasswordByGuidRequest
from seerr.models.create_auth_reset_password_request import CreateAuthResetPasswordRequest as CreateAuthResetPasswordRequest
from seerr.models.create_issue_comment_request import CreateIssueCommentRequest as CreateIssueCommentRequest
from seerr.models.create_issue_request import CreateIssueRequest as CreateIssueRequest
from seerr.models.create_jellyfin_sync_request import CreateJellyfinSyncRequest as CreateJellyfinSyncRequest
from seerr.models.create_jobs_schedule_request import CreateJobsScheduleRequest as CreateJobsScheduleRequest
from seerr.models.create_media_by_status_request import CreateMediaByStatusRequest as CreateMediaByStatusRequest
from seerr.models.create_request_request import CreateRequestRequest as CreateRequestRequest
from seerr.models.create_request_request_seasons import CreateRequestRequestSeasons as CreateRequestRequestSeasons
from seerr.models.create_user_import_from_jellyfin_request import CreateUserImportFromJellyfinRequest as CreateUserImportFromJellyfinRequest
from seerr.models.create_user_import_from_plex_request import CreateUserImportFromPlexRequest as CreateUserImportFromPlexRequest
from seerr.models.create_user_register_push_subscription_request import CreateUserRegisterPushSubscriptionRequest as CreateUserRegisterPushSubscriptionRequest
from seerr.models.create_user_request import CreateUserRequest as CreateUserRequest
from seerr.models.create_user_settings_linked_accounts_jellyfin_request import CreateUserSettingsLinkedAccountsJellyfinRequest as CreateUserSettingsLinkedAccountsJellyfinRequest
from seerr.models.create_user_settings_password_request import CreateUserSettingsPasswordRequest as CreateUserSettingsPasswordRequest
from seerr.models.create_user_settings_permissions_request import CreateUserSettingsPermissionsRequest as CreateUserSettingsPermissionsRequest
from seerr.models.credit_cast import CreditCast as CreditCast
from seerr.models.credit_crew import CreditCrew as CreditCrew
from seerr.models.crew import Crew as Crew
from seerr.models.discord_settings import DiscordSettings as DiscordSettings
from seerr.models.discord_settings_options import DiscordSettingsOptions as DiscordSettingsOptions
from seerr.models.discover_slider import DiscoverSlider as DiscoverSlider
from seerr.models.episode import Episode as Episode
from seerr.models.external_ids import ExternalIds as ExternalIds
from seerr.models.genre import Genre as Genre
from seerr.models.get_about2_xx_response import GetAbout2XXResponse as GetAbout2XXResponse
from seerr.models.get_blocklist2_xx_response import GetBlocklist2XXResponse as GetBlocklist2XXResponse
from seerr.models.get_blocklist2_xx_response_results_inner import GetBlocklist2XXResponseResultsInner as GetBlocklist2XXResponseResultsInner
from seerr.models.get_cache2_xx_response import GetCache2XXResponse as GetCache2XXResponse
from seerr.models.get_cache2_xx_response_api_caches_inner import GetCache2XXResponseApiCachesInner as GetCache2XXResponseApiCachesInner
from seerr.models.get_cache2_xx_response_api_caches_inner_stats import GetCache2XXResponseApiCachesInnerStats as GetCache2XXResponseApiCachesInnerStats
from seerr.models.get_cache2_xx_response_dns_cache import GetCache2XXResponseDnsCache as GetCache2XXResponseDnsCache
from seerr.models.get_cache2_xx_response_dns_cache_entries_value import GetCache2XXResponseDnsCacheEntriesValue as GetCache2XXResponseDnsCacheEntriesValue
from seerr.models.get_cache2_xx_response_dns_cache_entries_value_addresses import GetCache2XXResponseDnsCacheEntriesValueAddresses as GetCache2XXResponseDnsCacheEntriesValueAddresses
from seerr.models.get_cache2_xx_response_dns_cache_stats import GetCache2XXResponseDnsCacheStats as GetCache2XXResponseDnsCacheStats
from seerr.models.get_cache2_xx_response_image_cache import GetCache2XXResponseImageCache as GetCache2XXResponseImageCache
from seerr.models.get_cache2_xx_response_image_cache_tmdb import GetCache2XXResponseImageCacheTmdb as GetCache2XXResponseImageCacheTmdb
from seerr.models.get_certifications_movie500_response import GetCertificationsMovie500Response as GetCertificationsMovie500Response
from seerr.models.get_discover_movies2_xx_response import GetDiscoverMovies2XXResponse as GetDiscoverMovies2XXResponse
from seerr.models.get_discover_movies_genre_by_genre_id2_xx_response import GetDiscoverMoviesGenreByGenreId2XXResponse as GetDiscoverMoviesGenreByGenreId2XXResponse
from seerr.models.get_discover_movies_language_by_language2_xx_response import GetDiscoverMoviesLanguageByLanguage2XXResponse as GetDiscoverMoviesLanguageByLanguage2XXResponse
from seerr.models.get_discover_movies_studio_by_studio_id2_xx_response import GetDiscoverMoviesStudioByStudioId2XXResponse as GetDiscoverMoviesStudioByStudioId2XXResponse
from seerr.models.get_discover_tv2_xx_response import GetDiscoverTv2XXResponse as GetDiscoverTv2XXResponse
from seerr.models.get_discover_tv_genre_by_genre_id2_xx_response import GetDiscoverTvGenreByGenreId2XXResponse as GetDiscoverTvGenreByGenreId2XXResponse
from seerr.models.get_discover_tv_language_by_language2_xx_response import GetDiscoverTvLanguageByLanguage2XXResponse as GetDiscoverTvLanguageByLanguage2XXResponse
from seerr.models.get_discover_tv_network_by_network_id2_xx_response import GetDiscoverTvNetworkByNetworkId2XXResponse as GetDiscoverTvNetworkByNetworkId2XXResponse
from seerr.models.get_issue2_xx_response import GetIssue2XXResponse as GetIssue2XXResponse
from seerr.models.get_issue_count2_xx_response import GetIssueCount2XXResponse as GetIssueCount2XXResponse
from seerr.models.get_jellyfin_sync2_xx_response import GetJellyfinSync2XXResponse as GetJellyfinSync2XXResponse
from seerr.models.get_media2_xx_response import GetMedia2XXResponse as GetMedia2XXResponse
from seerr.models.get_media_watch_data2_xx_response import GetMediaWatchData2XXResponse as GetMediaWatchData2XXResponse
from seerr.models.get_media_watch_data2_xx_response_data import GetMediaWatchData2XXResponseData as GetMediaWatchData2XXResponseData
from seerr.models.get_movie_ratings2_xx_response import GetMovieRatings2XXResponse as GetMovieRatings2XXResponse
from seerr.models.get_movie_ratingscombined2_xx_response import GetMovieRatingscombined2XXResponse as GetMovieRatingscombined2XXResponse
from seerr.models.get_movie_ratingscombined2_xx_response_imdb import GetMovieRatingscombined2XXResponseImdb as GetMovieRatingscombined2XXResponseImdb
from seerr.models.get_person_combined_credits2_xx_response import GetPersonCombinedCredits2XXResponse as GetPersonCombinedCredits2XXResponse
from seerr.models.get_plex_sync2_xx_response import GetPlexSync2XXResponse as GetPlexSync2XXResponse
from seerr.models.get_request_count2_xx_response import GetRequestCount2XXResponse as GetRequestCount2XXResponse
from seerr.models.get_search2_xx_response import GetSearch2XXResponse as GetSearch2XXResponse
from seerr.models.get_search2_xx_response_results_inner import GetSearch2XXResponseResultsInner as GetSearch2XXResponseResultsInner
from seerr.models.get_search_company2_xx_response import GetSearchCompany2XXResponse as GetSearchCompany2XXResponse
from seerr.models.get_search_keyword2_xx_response import GetSearchKeyword2XXResponse as GetSearchKeyword2XXResponse
from seerr.models.get_service_radarr_by_radarr_id2_xx_response import GetServiceRadarrByRadarrId2XXResponse as GetServiceRadarrByRadarrId2XXResponse
from seerr.models.get_service_sonarr_by_sonarr_id2_xx_response import GetServiceSonarrBySonarrId2XXResponse as GetServiceSonarrBySonarrId2XXResponse
from seerr.models.get_status2_xx_response import GetStatus2XXResponse as GetStatus2XXResponse
from seerr.models.get_status_appdata2_xx_response import GetStatusAppdata2XXResponse as GetStatusAppdata2XXResponse
from seerr.models.get_tv_ratings2_xx_response import GetTvRatings2XXResponse as GetTvRatings2XXResponse
from seerr.models.get_user2_xx_response import GetUser2XXResponse as GetUser2XXResponse
from seerr.models.get_user_push_subscriptions2_xx_response import GetUserPushSubscriptions2XXResponse as GetUserPushSubscriptions2XXResponse
from seerr.models.get_user_quota2_xx_response import GetUserQuota2XXResponse as GetUserQuota2XXResponse
from seerr.models.get_user_quota2_xx_response_movie import GetUserQuota2XXResponseMovie as GetUserQuota2XXResponseMovie
from seerr.models.get_user_requests2_xx_response import GetUserRequests2XXResponse as GetUserRequests2XXResponse
from seerr.models.get_user_settings_password2_xx_response import GetUserSettingsPassword2XXResponse as GetUserSettingsPassword2XXResponse
from seerr.models.get_user_settings_permissions2_xx_response import GetUserSettingsPermissions2XXResponse as GetUserSettingsPermissions2XXResponse
from seerr.models.get_user_watch_data2_xx_response import GetUserWatchData2XXResponse as GetUserWatchData2XXResponse
from seerr.models.get_user_watchlist2_xx_response import GetUserWatchlist2XXResponse as GetUserWatchlist2XXResponse
from seerr.models.get_user_watchlist2_xx_response_results_inner import GetUserWatchlist2XXResponseResultsInner as GetUserWatchlist2XXResponseResultsInner
from seerr.models.gotify_settings import GotifySettings as GotifySettings
from seerr.models.gotify_settings_options import GotifySettingsOptions as GotifySettingsOptions
from seerr.models.issue import Issue as Issue
from seerr.models.issue_comment import IssueComment as IssueComment
from seerr.models.jellyfin_library import JellyfinLibrary as JellyfinLibrary
from seerr.models.jellyfin_settings import JellyfinSettings as JellyfinSettings
from seerr.models.job import Job as Job
from seerr.models.keyword import Keyword as Keyword
from seerr.models.list_discover_genreslider_movie2_xx_response_inner import ListDiscoverGenresliderMovie2XXResponseInner as ListDiscoverGenresliderMovie2XXResponseInner
from seerr.models.list_genres_movie2_xx_response_inner import ListGenresMovie2XXResponseInner as ListGenresMovie2XXResponseInner
from seerr.models.list_jellyfin_users2_xx_response_inner import ListJellyfinUsers2XXResponseInner as ListJellyfinUsers2XXResponseInner
from seerr.models.list_languages2_xx_response_inner import ListLanguages2XXResponseInner as ListLanguages2XXResponseInner
from seerr.models.list_logs2_xx_response_inner import ListLogs2XXResponseInner as ListLogs2XXResponseInner
from seerr.models.list_notifications_pushover_sounds2_xx_response_inner import ListNotificationsPushoverSounds2XXResponseInner as ListNotificationsPushoverSounds2XXResponseInner
from seerr.models.list_plex_users2_xx_response_inner import ListPlexUsers2XXResponseInner as ListPlexUsers2XXResponseInner
from seerr.models.list_regions2_xx_response_inner import ListRegions2XXResponseInner as ListRegions2XXResponseInner
from seerr.models.main_settings import MainSettings as MainSettings
from seerr.models.media_info import MediaInfo as MediaInfo
from seerr.models.media_request import MediaRequest as MediaRequest
from seerr.models.media_request_modified_by import MediaRequestModifiedBy as MediaRequestModifiedBy
from seerr.models.metadata_settings import MetadataSettings as MetadataSettings
from seerr.models.metadata_settings_settings import MetadataSettingsSettings as MetadataSettingsSettings
from seerr.models.movie_details import MovieDetails as MovieDetails
from seerr.models.movie_details_collection import MovieDetailsCollection as MovieDetailsCollection
from seerr.models.movie_details_credits import MovieDetailsCredits as MovieDetailsCredits
from seerr.models.movie_details_production_countries_inner import MovieDetailsProductionCountriesInner as MovieDetailsProductionCountriesInner
from seerr.models.movie_details_releases import MovieDetailsReleases as MovieDetailsReleases
from seerr.models.movie_details_releases_results_inner import MovieDetailsReleasesResultsInner as MovieDetailsReleasesResultsInner
from seerr.models.movie_details_releases_results_inner_release_dates_inner import MovieDetailsReleasesResultsInnerReleaseDatesInner as MovieDetailsReleasesResultsInnerReleaseDatesInner
from seerr.models.movie_result import MovieResult as MovieResult
from seerr.models.network import Network as Network
from seerr.models.network_settings import NetworkSettings as NetworkSettings
from seerr.models.network_settings_dns_cache import NetworkSettingsDnsCache as NetworkSettingsDnsCache
from seerr.models.network_settings_proxy import NetworkSettingsProxy as NetworkSettingsProxy
from seerr.models.notification_agent_types import NotificationAgentTypes as NotificationAgentTypes
from seerr.models.notification_email_settings import NotificationEmailSettings as NotificationEmailSettings
from seerr.models.notification_email_settings_options import NotificationEmailSettingsOptions as NotificationEmailSettingsOptions
from seerr.models.ntfy_settings import NtfySettings as NtfySettings
from seerr.models.ntfy_settings_options import NtfySettingsOptions as NtfySettingsOptions
from seerr.models.override_rule import OverrideRule as OverrideRule
from seerr.models.page_info import PageInfo as PageInfo
from seerr.models.person_details import PersonDetails as PersonDetails
from seerr.models.person_result import PersonResult as PersonResult
from seerr.models.person_result_known_for_inner import PersonResultKnownForInner as PersonResultKnownForInner
from seerr.models.plex_connection import PlexConnection as PlexConnection
from seerr.models.plex_device import PlexDevice as PlexDevice
from seerr.models.plex_library import PlexLibrary as PlexLibrary
from seerr.models.plex_settings import PlexSettings as PlexSettings
from seerr.models.production_company import ProductionCompany as ProductionCompany
from seerr.models.public_settings import PublicSettings as PublicSettings
from seerr.models.pushbullet_settings import PushbulletSettings as PushbulletSettings
from seerr.models.pushbullet_settings_options import PushbulletSettingsOptions as PushbulletSettingsOptions
from seerr.models.pushover_settings import PushoverSettings as PushoverSettings
from seerr.models.pushover_settings_options import PushoverSettingsOptions as PushoverSettingsOptions
from seerr.models.put_user_request import PutUserRequest as PutUserRequest
from seerr.models.radarr_settings import RadarrSettings as RadarrSettings
from seerr.models.related_video import RelatedVideo as RelatedVideo
from seerr.models.season import Season as Season
from seerr.models.servarr_tag import ServarrTag as ServarrTag
from seerr.models.service_profile import ServiceProfile as ServiceProfile
from seerr.models.slack_settings import SlackSettings as SlackSettings
from seerr.models.slack_settings_options import SlackSettingsOptions as SlackSettingsOptions
from seerr.models.sonarr_series import SonarrSeries as SonarrSeries
from seerr.models.sonarr_series_add_options_inner import SonarrSeriesAddOptionsInner as SonarrSeriesAddOptionsInner
from seerr.models.sonarr_series_images_inner import SonarrSeriesImagesInner as SonarrSeriesImagesInner
from seerr.models.sonarr_series_ratings_inner import SonarrSeriesRatingsInner as SonarrSeriesRatingsInner
from seerr.models.sonarr_series_seasons_inner import SonarrSeriesSeasonsInner as SonarrSeriesSeasonsInner
from seerr.models.sonarr_settings import SonarrSettings as SonarrSettings
from seerr.models.spoken_language import SpokenLanguage as SpokenLanguage
from seerr.models.tautulli_settings import TautulliSettings as TautulliSettings
from seerr.models.telegram_settings import TelegramSettings as TelegramSettings
from seerr.models.telegram_settings_options import TelegramSettingsOptions as TelegramSettingsOptions
from seerr.models.test_metadatas2_xx_response import TestMetadatas2XXResponse as TestMetadatas2XXResponse
from seerr.models.test_metadatas_request import TestMetadatasRequest as TestMetadatasRequest
from seerr.models.test_radarr2_xx_response import TestRadarr2XXResponse as TestRadarr2XXResponse
from seerr.models.test_radarr_request import TestRadarrRequest as TestRadarrRequest
from seerr.models.tv_details import TvDetails as TvDetails
from seerr.models.tv_details_content_ratings import TvDetailsContentRatings as TvDetailsContentRatings
from seerr.models.tv_details_content_ratings_results_inner import TvDetailsContentRatingsResultsInner as TvDetailsContentRatingsResultsInner
from seerr.models.tv_details_created_by_inner import TvDetailsCreatedByInner as TvDetailsCreatedByInner
from seerr.models.tv_result import TvResult as TvResult
from seerr.models.update_discover_request import UpdateDiscoverRequest as UpdateDiscoverRequest
from seerr.models.update_request_request import UpdateRequestRequest as UpdateRequestRequest
from seerr.models.user import User as User
from seerr.models.user_settings import UserSettings as UserSettings
from seerr.models.user_settings_notifications import UserSettingsNotifications as UserSettingsNotifications
from seerr.models.watch_provider_details import WatchProviderDetails as WatchProviderDetails
from seerr.models.watch_provider_region import WatchProviderRegion as WatchProviderRegion
from seerr.models.watch_providers_inner import WatchProvidersInner as WatchProvidersInner
from seerr.models.watchlist import Watchlist as Watchlist
from seerr.models.web_push_settings import WebPushSettings as WebPushSettings
from seerr.models.webhook_settings import WebhookSettings as WebhookSettings
from seerr.models.webhook_settings_options import WebhookSettingsOptions as WebhookSettingsOptions

