# coding: utf-8

"""
    Seerr API

    This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

    The version of the OpenAPI document: v3.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from seerr.models.jellyfin_library import JellyfinLibrary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JellyfinSettings(BaseModel):
    """
    JellyfinSettings
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Main Server"]})
    hostname: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["http://my.jellyfin.host"]})
    external_hostname: Optional[StrictStr] = Field(default=None, alias="externalHostname", json_schema_extra={"examples": ["http://my.jellyfin.host"]})
    jellyfin_forgot_password_url: Optional[StrictStr] = Field(default=None, alias="jellyfinForgotPasswordUrl", json_schema_extra={"examples": ["http://my.jellyfin.host/web/index.html#!/forgotpassword.html"]})
    admin_user: Optional[StrictStr] = Field(default=None, alias="adminUser", json_schema_extra={"examples": ["admin"]})
    admin_pass: Optional[StrictStr] = Field(default=None, alias="adminPass", json_schema_extra={"examples": ["mypassword"]})
    libraries: Optional[List[JellyfinLibrary]] = None
    server_id: Optional[StrictStr] = Field(default=None, alias="serverID")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "hostname", "externalHostname", "jellyfinForgotPasswordUrl", "adminUser", "adminPass", "libraries", "serverID"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JellyfinSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "name",
            "libraries",
            "server_id",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in libraries (list)
        _items = []
        if self.libraries:
            for _item_libraries in self.libraries:
                if _item_libraries:
                    _items.append(_item_libraries.to_dict())
            _dict['libraries'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JellyfinSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "hostname": obj.get("hostname"),
            "externalHostname": obj.get("externalHostname"),
            "jellyfinForgotPasswordUrl": obj.get("jellyfinForgotPasswordUrl"),
            "adminUser": obj.get("adminUser"),
            "adminPass": obj.get("adminPass"),
            "libraries": [JellyfinLibrary.from_dict(_item) for _item in obj["libraries"]] if obj.get("libraries") is not None else None,
            "serverID": obj.get("serverID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


