# coding: utf-8

"""
    Seerr API

    This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

    The version of the OpenAPI document: v3.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NotificationEmailSettingsOptions(BaseModel):
    """
    NotificationEmailSettingsOptions
    """ # noqa: E501
    email_from: Optional[StrictStr] = Field(default=None, alias="emailFrom", json_schema_extra={"examples": ["no-reply@example.com"]})
    sender_name: Optional[StrictStr] = Field(default=None, alias="senderName", json_schema_extra={"examples": ["Seerr"]})
    smtp_host: Optional[StrictStr] = Field(default=None, alias="smtpHost", json_schema_extra={"examples": ["127.0.0.1"]})
    smtp_port: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="smtpPort", json_schema_extra={"examples": [465]})
    secure: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    ignore_tls: Optional[StrictBool] = Field(default=None, alias="ignoreTls", json_schema_extra={"examples": [False]})
    require_tls: Optional[StrictBool] = Field(default=None, alias="requireTls", json_schema_extra={"examples": [False]})
    auth_user: Optional[StrictStr] = Field(default=None, alias="authUser")
    auth_pass: Optional[StrictStr] = Field(default=None, alias="authPass")
    allow_self_signed: Optional[StrictBool] = Field(default=None, alias="allowSelfSigned", json_schema_extra={"examples": [False]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["emailFrom", "senderName", "smtpHost", "smtpPort", "secure", "ignoreTls", "requireTls", "authUser", "authPass", "allowSelfSigned"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationEmailSettingsOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if auth_user (nullable) is None
        # and model_fields_set contains the field
        if self.auth_user is None and "auth_user" in self.model_fields_set:
            _dict['authUser'] = None

        # set to None if auth_pass (nullable) is None
        # and model_fields_set contains the field
        if self.auth_pass is None and "auth_pass" in self.model_fields_set:
            _dict['authPass'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationEmailSettingsOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "emailFrom": obj.get("emailFrom"),
            "senderName": obj.get("senderName"),
            "smtpHost": obj.get("smtpHost"),
            "smtpPort": obj.get("smtpPort"),
            "secure": obj.get("secure"),
            "ignoreTls": obj.get("ignoreTls"),
            "requireTls": obj.get("requireTls"),
            "authUser": obj.get("authUser"),
            "authPass": obj.get("authPass"),
            "allowSelfSigned": obj.get("allowSelfSigned")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


