# coding: utf-8

"""
    Seerr API

    This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

    The version of the OpenAPI document: v3.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserSettings(BaseModel):
    """
    UserSettings
    """ # noqa: E501
    username: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Mr User"]})
    email: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["user@example.com"]})
    locale: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["en"]})
    discover_region: Optional[StrictStr] = Field(default=None, alias="discoverRegion", json_schema_extra={"examples": ["US"]})
    streaming_region: Optional[StrictStr] = Field(default=None, alias="streamingRegion", json_schema_extra={"examples": ["US"]})
    original_language: Optional[StrictStr] = Field(default=None, alias="originalLanguage", json_schema_extra={"examples": ["en"]})
    movie_quota_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum number of movie requests allowed", alias="movieQuotaLimit", json_schema_extra={"examples": [10]})
    movie_quota_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Time period in days for movie quota", alias="movieQuotaDays", json_schema_extra={"examples": [30]})
    tv_quota_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum number of TV requests allowed", alias="tvQuotaLimit", json_schema_extra={"examples": [5]})
    tv_quota_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Time period in days for TV quota", alias="tvQuotaDays", json_schema_extra={"examples": [14]})
    global_movie_quota_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Global movie quota days setting", alias="globalMovieQuotaDays", json_schema_extra={"examples": [30]})
    global_movie_quota_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Global movie quota limit setting", alias="globalMovieQuotaLimit", json_schema_extra={"examples": [10]})
    global_tv_quota_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Global TV quota limit setting", alias="globalTvQuotaLimit", json_schema_extra={"examples": [5]})
    global_tv_quota_days: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Global TV quota days setting", alias="globalTvQuotaDays", json_schema_extra={"examples": [14]})
    watchlist_sync_movies: Optional[StrictBool] = Field(default=None, description="Enable watchlist sync for movies", alias="watchlistSyncMovies", json_schema_extra={"examples": [True]})
    watchlist_sync_tv: Optional[StrictBool] = Field(default=None, description="Enable watchlist sync for TV", alias="watchlistSyncTv", json_schema_extra={"examples": [False]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["username", "email", "locale", "discoverRegion", "streamingRegion", "originalLanguage", "movieQuotaLimit", "movieQuotaDays", "tvQuotaLimit", "tvQuotaDays", "globalMovieQuotaDays", "globalMovieQuotaLimit", "globalTvQuotaLimit", "globalTvQuotaDays", "watchlistSyncMovies", "watchlistSyncTv"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict['username'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        # set to None if discover_region (nullable) is None
        # and model_fields_set contains the field
        if self.discover_region is None and "discover_region" in self.model_fields_set:
            _dict['discoverRegion'] = None

        # set to None if streaming_region (nullable) is None
        # and model_fields_set contains the field
        if self.streaming_region is None and "streaming_region" in self.model_fields_set:
            _dict['streamingRegion'] = None

        # set to None if original_language (nullable) is None
        # and model_fields_set contains the field
        if self.original_language is None and "original_language" in self.model_fields_set:
            _dict['originalLanguage'] = None

        # set to None if movie_quota_limit (nullable) is None
        # and model_fields_set contains the field
        if self.movie_quota_limit is None and "movie_quota_limit" in self.model_fields_set:
            _dict['movieQuotaLimit'] = None

        # set to None if movie_quota_days (nullable) is None
        # and model_fields_set contains the field
        if self.movie_quota_days is None and "movie_quota_days" in self.model_fields_set:
            _dict['movieQuotaDays'] = None

        # set to None if tv_quota_limit (nullable) is None
        # and model_fields_set contains the field
        if self.tv_quota_limit is None and "tv_quota_limit" in self.model_fields_set:
            _dict['tvQuotaLimit'] = None

        # set to None if tv_quota_days (nullable) is None
        # and model_fields_set contains the field
        if self.tv_quota_days is None and "tv_quota_days" in self.model_fields_set:
            _dict['tvQuotaDays'] = None

        # set to None if global_movie_quota_days (nullable) is None
        # and model_fields_set contains the field
        if self.global_movie_quota_days is None and "global_movie_quota_days" in self.model_fields_set:
            _dict['globalMovieQuotaDays'] = None

        # set to None if global_movie_quota_limit (nullable) is None
        # and model_fields_set contains the field
        if self.global_movie_quota_limit is None and "global_movie_quota_limit" in self.model_fields_set:
            _dict['globalMovieQuotaLimit'] = None

        # set to None if global_tv_quota_limit (nullable) is None
        # and model_fields_set contains the field
        if self.global_tv_quota_limit is None and "global_tv_quota_limit" in self.model_fields_set:
            _dict['globalTvQuotaLimit'] = None

        # set to None if global_tv_quota_days (nullable) is None
        # and model_fields_set contains the field
        if self.global_tv_quota_days is None and "global_tv_quota_days" in self.model_fields_set:
            _dict['globalTvQuotaDays'] = None

        # set to None if watchlist_sync_movies (nullable) is None
        # and model_fields_set contains the field
        if self.watchlist_sync_movies is None and "watchlist_sync_movies" in self.model_fields_set:
            _dict['watchlistSyncMovies'] = None

        # set to None if watchlist_sync_tv (nullable) is None
        # and model_fields_set contains the field
        if self.watchlist_sync_tv is None and "watchlist_sync_tv" in self.model_fields_set:
            _dict['watchlistSyncTv'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "username": obj.get("username"),
            "email": obj.get("email"),
            "locale": obj.get("locale"),
            "discoverRegion": obj.get("discoverRegion"),
            "streamingRegion": obj.get("streamingRegion"),
            "originalLanguage": obj.get("originalLanguage"),
            "movieQuotaLimit": obj.get("movieQuotaLimit"),
            "movieQuotaDays": obj.get("movieQuotaDays"),
            "tvQuotaLimit": obj.get("tvQuotaLimit"),
            "tvQuotaDays": obj.get("tvQuotaDays"),
            "globalMovieQuotaDays": obj.get("globalMovieQuotaDays"),
            "globalMovieQuotaLimit": obj.get("globalMovieQuotaLimit"),
            "globalTvQuotaLimit": obj.get("globalTvQuotaLimit"),
            "globalTvQuotaDays": obj.get("globalTvQuotaDays"),
            "watchlistSyncMovies": obj.get("watchlistSyncMovies"),
            "watchlistSyncTv": obj.get("watchlistSyncTv")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


